#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path
from typing import Any

from graph_projection_lib import (
    DEFAULT_MANIFEST_PATH,
    ROOT,
    cypher_literal,
    read_jsonl,
    read_manifest,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Load the projected graph-v1 payload into Neo4j via cypher-shell.")
    parser.add_argument(
        "--manifest",
        default=str(DEFAULT_MANIFEST_PATH),
        help="Path to the JSON-compatible YAML import manifest.",
    )
    parser.add_argument(
        "--projection-dir",
        default=None,
        help="Override projection directory. Defaults to manifest output_dir.",
    )
    parser.add_argument(
        "--cypher-out",
        default=None,
        help="Override output Cypher path. Defaults to <projection-dir>/load-graph-v1.cypher.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Apply the generated Cypher with cypher-shell after writing it.",
    )
    parser.add_argument("--uri", default=os.getenv("NEO4J_URI", "bolt://localhost:7687"))
    parser.add_argument("--user", default=os.getenv("NEO4J_USER", "neo4j"))
    parser.add_argument("--password", default=os.getenv("NEO4J_PASSWORD"))
    parser.add_argument("--database", default=os.getenv("NEO4J_DATABASE", "neo4j"))
    return parser.parse_args()


def build_node_statement(node: dict[str, Any]) -> str:
    properties = {
        "display_label": node["display_label"],
        "node_type": node["node_type"],
        "promotion_state": node["promotion_state"],
        "source_bundle_ids": node["source_bundle_ids"],
        "source_sections": node["source_sections"],
        **node["properties"],
    }
    if node.get("source_status") is not None:
        properties["source_status"] = node["source_status"]
    return "\n".join(
        [
            f"MERGE (n:Imported {{id: {cypher_literal(node['id'])}}})",
            f"SET n:{node['node_type']}",
            f"SET n += {cypher_literal(properties)};",
        ]
    )


def build_edge_statement(edge: dict[str, Any]) -> str:
    properties = {
        "source_bundle_ids": edge["source_bundle_ids"],
        "source_fields": edge["source_fields"],
        **edge["properties"],
    }
    return "\n".join(
        [
            f"MATCH (source:Imported {{id: {cypher_literal(edge['source_id'])}}})",
            f"MATCH (target:Imported {{id: {cypher_literal(edge['target_id'])}}})",
            f"MERGE (source)-[r:{edge['relationship_type']}]->(target)",
            f"SET r += {cypher_literal(properties)};",
        ]
    )


def main() -> None:
    args = parse_args()
    manifest = read_manifest(Path(args.manifest).resolve())
    projection_dir = (
        (ROOT / manifest["output_dir"]).resolve()
        if args.projection_dir is None
        else Path(args.projection_dir).resolve()
    )
    cypher_out = (
        projection_dir / "load-graph-v1.cypher"
        if args.cypher_out is None
        else Path(args.cypher_out).resolve()
    )

    nodes = read_jsonl(projection_dir / "nodes.jsonl")
    edges = read_jsonl(projection_dir / "edges.jsonl")

    statements = [
        "// Auto-generated by scripts/load_neo4j_v1.py",
        "CREATE CONSTRAINT imported_id_unique IF NOT EXISTS FOR (n:Imported) REQUIRE n.id IS UNIQUE;",
        "",
        "// Nodes",
    ]
    statements.extend(build_node_statement(node) for node in nodes)
    statements.extend(["", "// Relationships"])
    statements.extend(build_edge_statement(edge) for edge in edges)

    cypher_out.parent.mkdir(parents=True, exist_ok=True)
    cypher_out.write_text("\n\n".join(statements) + "\n")

    if not args.apply:
        return
    if not args.password:
        raise SystemExit("NEO4J_PASSWORD is required when --apply is used.")

    subprocess.run(
        [
            "cypher-shell",
            "-a",
            args.uri,
            "-u",
            args.user,
            "-p",
            args.password,
            "-d",
            args.database,
            "-f",
            str(cypher_out),
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
